name: C4
favicon: null
layout_spectrum: 0.99246
typography_spectrum: 1
title: Centre for Critical Care Collaboration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272727'
    - '#f3cb6d'
    - '#fcfbfd'
    - '#846f42'
    - '#919192'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
